#!/usr/bin/env python3
"""
scripts/generate_ai_index.py
============================
Auto-generates `AI_INDEX.md` at the repository root.
Scans folders, reads DATAINFO.md catalogs, indexes engine entry points,
and summarizes the project architecture into a high-density, token-efficient
document (~1,500 tokens) for AI coding assistants.
"""

import os
import sys
from pathlib import Path
from datetime import datetime

ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT_DIR / "AI_INDEX.md"

IGNORE_DIRS = {
    ".git", ".turbo", "node_modules", "dist", "__pycache__",
    ".vscode", ".idea", "coverage", ".next", ".githooks"
}


def scan_directory_tree(base_dir: Path, max_depth: int = 3) -> list[str]:
    """Generates a compact, indented tree structure of the repository."""
    lines = []

    def _walk(current: Path, prefix: str, depth: int):
        if depth > max_depth:
            return
        entries = sorted(
            [e for e in current.iterdir() if e.name not in IGNORE_DIRS and not e.name.startswith(".")],
            key=lambda x: (not x.is_dir(), x.name.lower())
        )
        for i, entry in enumerate(entries):
            is_last = (i == len(entries) - 1)
            connector = "└── " if is_last else "├── "
            child_prefix = "    " if is_last else "│   "

            if entry.is_dir():
                lines.append(f"{prefix}{connector}{entry.name}/")
                _walk(entry, prefix + child_prefix, depth + 1)
            else:
                # Include significant entry points and config files
                if entry.name in {"package.json", "pyproject.toml", "Makefile", "cli.py", "RULESET.md", "DATAINFO.md"}:
                    lines.append(f"{prefix}{connector}{entry.name}")

    lines.append("WEFES_NEXUS_NEPAL_GULMI/")
    _walk(base_dir, "", 1)
    return lines


def collect_datainfo(base_dir: Path) -> list[dict]:
    """Finds all DATAINFO.md files and extracts folder summary info."""
    data_info_list = []
    data_dir = base_dir / "data"
    if not data_dir.exists():
        return data_info_list

    for path in sorted(data_dir.rglob("DATAINFO.md")):
        rel_dir = path.parent.relative_to(base_dir)
        classification = "Unknown"
        summary = ""
        try:
            content = path.read_text(encoding="utf-8")
            for line in content.splitlines():
                if "Data Type" in line:
                    classification = line.split(":", 1)[-1].strip(" *[]")
                elif line.startswith("## 1.") or line.startswith("# "):
                    if not summary:
                        summary = line.strip("# ").strip()
        except Exception:
            pass

        data_info_list.append({
            "path": str(rel_dir),
            "type": classification,
            "summary": summary or rel_dir.name
        })
    return data_info_list


def main():
    tree_lines = scan_directory_tree(ROOT_DIR, max_depth=3)
    data_info = collect_datainfo(ROOT_DIR)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    doc = f"""# WEFES PLATFORM: AI CONTEXT & ARCHITECTURE MAP
> Auto-generated on {now}. DO NOT EDIT DIRECTLY. Updated via `scripts/generate_ai_index.py`.
> This file is a high-density, token-optimized context anchor for AI assistants.

---

## 1. High-Level System Blueprint
- **Domain**: Water-Energy-Food-Ecosystem-Society (WEFES) Nexus Modeling for Nepal (Gulmi District).
- **Architecture**: Polyglot Monorepo with autonomous, headless scientific engines.
- **Languages**: TypeScript (Web portal, Agro-Nexus simulator) & Python (Geospatial GIS, D8 stream routing, Hydropower).

---

## 2. Active Engines & Entry Points

| Engine | Language | Location | CLI / Execution Command | Primary Responsibility |
|---|---|---|---|---|
| **Water (Hydro)** | Python | `engines/water/hydro/` | `python3 engines/water/hydro/cli.py` | 6-step D8 Priority-Flood, WECS/NEA hydrology, DOED E-flow, 500m reach energy |
| **Nexus Core** | TypeScript | `engines/nexus/` | `pnpm --filter @wefes/wefes-engine test` | Cross-pillar simulation, 5-pillar domain models (Water, Food, Energy, Eco, Social) |
| **API Gateway** | TypeScript | `apps/api/` | `pnpm --filter api dev` | Data delivery endpoints, query caching, simulation dispatch |
| **Web Portal** | TypeScript | `apps/web/` | `pnpm --filter web dev` | Interactive Leaflet map, dynamic subfilter legends, policy simulator |

---

## 3. Data Governance & Classification (`data/`)

| Tier | Path | Access Rule | Purpose |
|---|---|---|---|
| **Real** | `data/real/` | **READ-ONLY** | Official observed records (DHM gauges #410/#430, MoALD census, official boundaries) |
| **Calculated** | `data/calculated/` | **REPRODUCIBLE** | Deterministic outputs generated by engines (screened reaches, downscaled rainfall) |
| **Proxy** | `data/proxy/` | **EXPLICIT SURROGATE** | Assumptions/estimates where empirical data is missing (rural tariffs, temperature bounds) |

### Discovered Data Catalogs:
"""
    if data_info:
        doc += "| Subfolder | Classification | Description |\n|---|---|---|\n"
        for d in data_info:
            doc += f"| `{d['path']}` | **{d['type']}** | {d['summary']} |\n"
    else:
        doc += "_Data catalog initialization in progress._\n"

    doc += """
---

## 4. Non-Negotiable Engineering Rules (`RULESET.md`)
1. **Zero Inward Code Imports**: Engines NEVER import code from `apps/` or `packages/`.
2. **Zero Hardcoded Data**: All domain constants, coordinates, and thresholds MUST be read from `data/`.
3. **In-Code Provenance**: Every file consuming data MUST have a top-level `// [DATA PROVENANCE]` comment.
4. **Git Hygiene**: Never commit rasters >10 MB (use `data/manifest.json`). No direct pushes to `main`.
5. **Atomic Commits**: Maximum 400 net lines of change per commit.
6. **Dual Documentation**: Every directory must contain `README.md` and `RULES.md`.

---

## 5. Directory Structure Overview
```text
""" + "\n".join(tree_lines[:70]) + "\n```\n"

    OUTPUT_FILE.write_text(doc, encoding="utf-8")
    print(f"--> Successfully generated {OUTPUT_FILE.name} ({len(doc.splitlines())} lines)")


if __name__ == "__main__":
    main()
